// Code generated by go2go; DO NOT EDIT.


//line funcs.go2:1
package futures

//line funcs.go2:1
import (
//line funcs.go2:1
 "context"
//line funcs.go2:1
 "fmt"
//line funcs.go2:1
 "github.com/anacrolix/missinggo/slices"
//line funcs.go2:1
 "github.com/bradfitz/iter"
//line funcs.go2:1
 "sort"
//line funcs.go2:1
 "sync"
//line funcs.go2:1
 "testing"
//line funcs.go2:1
 "time"
//line funcs.go2:1
)

//line funcs.go2:1
var _ = context.Background
//line funcs.go2:1
var _ = fmt.Errorf
//line funcs.go2:1
var _ = slices.FilterInPlace
//line funcs.go2:1
var _ = iter.N

//line funcs.go2:1
type _ sort.Float64Slice
//line funcs.go2:1
type _ sync.Cond

//line funcs.go2:1
var _ = testing.AllocsPerRun

//line funcs.go2:1
const _ = time.ANSIC
